### ISSUE TITLE
zim desktop refresh workaround (switching between pages works)

### ISSUE THREAD

**Issue by elisdg** [jakykong/vim-zim#6]
[https://github.com/jakykong/vim-zim/blob/master/README.md](https://github.com/jakykong/vim-zim/blob/master/README.md)
just wanted to note:
I'm on debian with Zim 0.68
Switching between two pages (e.g.: <alt>+<pg up> and <alt>+<pg down> does refresh the content of the page, there is no need to restart!
thx for creating this vim plugin!!

**Comment by luffah** [comment]
I tested and agree. Once rtp is updated, the initialisation is done. For zim files, you just need to do `:e!`.
I updated this on my vim-zim fork.  Feel free to add some comments on feature i added (https://github.com/luffah/vim-zim).

**Comment by jakykong** [comment]
@luffah fixed this - most recent changes from luffa/vim-zim are here, considering this issue closed.
